spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pagamentos
    username: postgres
    password: arthur
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true